"""
Django settings for muxi_shop_api2 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
import apps as django_apps
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#把apps，加入到项目根的搜索路径，导入的时候，可以直接从源码包中导入
sys.path.insert(0,BASE_DIR)
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ldy144q7h=7_06ea*@o!2@hkzfo&2q5cta0%%u&ot*gywl2+i&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*",]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'user',
    'order',
    'goods',
    'comment',
    'menu',
    'rest_framework',
    'address',
    'corsheaders',
    'pay',
]
#解决跨域的一个插件
#pip install django-cors-headers
#允许所有域名跨域
CORS_ORIGIN_ALLOW_ALL=True
#允许携带cookie
CORS_ALLOW_CREDENTIALS=True




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'muxi_shop_api2.urls'
# 我想说 阳明心学
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'muxi_shop_api2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "muxueshop",
        'USER':"root",
        'PASSWORD':"123456",
        'HOST':"20.20.20.133",
        'PORT':'3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
#这个是图片的访问路径
STATIC_URL = 'static/'
#需要配置文件所在路径
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#静态文件服务器配置

IMAGE_URL="http://localhost:8000/static/product_images/"

REST_FRAMEWORK ={
    # "DEFAULT_AUTHENTICATION_CLASSES":['utils.jwt_auth.JwtQueryParamAuthentication'],
    "DEFAULT_AUTHENTICATION_CLASSES":['utils.jwt_auth.JwtHeaderAuthentication']
}

# 支付宝沙箱环境配置
APPID="9021000132633995"
ALI_PUB_KEY_PATH=os.path.join(BASE_DIR,"apps/pay/keys/alipay_key.txt")
PRIVATE_KEY_PATH=os.path.join(BASE_DIR,"apps/pay/keys/private_key.txt")

# 异步接收url
APP_NOTIFY_URL="http://127.0.0.1:8000/alipay/return"

# 同步接收url就是用户支付成功之后要跳转到的页面
RETURN_URL="http://127.0.0.1:8000/pay/alipay/return"
# 是否是开发环境
ALIPAY_DEBUG=True